interface HistoricalFigure {
  name: string;
  birthYear: string;
  deathYear: string;
  description: string;
}

// export const people: Person[] = [
export const people: HistoricalFigure[] = [
  { name: "St. Peter", birthYear: "-000001", deathYear: "0064", description:" First Pope" },      
  { name: "St. Paul", birthYear: "0005", deathYear:  "0067", description:" Apostle to the Gentiles" },        
  { name: "St. Augustine of Hippo", birthYear: "0354", deathYear: "0430", description: "One of the most influential theologians and philosophers of the early Church, St. Augustine's writings, including 'Confessions' and 'City of God,' helped shape Western Christianity and philosophy. Originally a skeptic, he converted to Christianity and became the Bishop of Hippo." },
  { name: "St. Jerome", birthYear:  "0347", deathYear:  "0420", description:" Translator of the Bible" },   
  { name: "St. Gregory the Great", birthYear:  "0540", deathYear:  "0604", description:" Pope and Doctor of the Church" },  
  { name: "St. Benedict of Nursia", birthYear:  "0480", deathYear:  "0547", description:" Founder of Western monasticism" }, 
  { name: "St. Francis of Assisi", birthYear: "1181", deathYear: "1226", description: "Founder of the Franciscan Order, St. Francis is known for his love of nature, humility, and devotion to a life of poverty. He is often depicted with animals and is the patron saint of ecology and animals." },
  { name: "St. Dominic", birthYear: "1170", deathYear: "1221", description:" Founder of the Dominicans" }, 
  { name: "St. Thomas Aquinas", birthYear: "1225", deathYear: "1274", description:" Doctor of the Church, theologian" },   
  { name: "St. Clare of Assisi", birthYear: "1194", deathYear: "1253", description: "A close follower of St. Francis, St. Clare founded the Order of Poor Ladies (later known as the Poor Clares) and led a life of austere poverty and prayer. She is known for her deep faith and dedication to service and contemplation." },
  { name: "St. Catherine of Siena", birthYear: "1347", deathYear: "1380", description: "A mystic and Doctor of the Church, St. Catherine played a significant role in advising Church leaders during the Avignon Papacy. She is known for her intense visions, letters to the Pope, and work in bringing about church reforms and spiritual renewal." },
  { name: "St. Teresa of Ávila", birthYear: "1515", deathYear: "1582", description: "A Carmelite nun, mystic, and reformer, St. Teresa was a prominent figure in the Counter-Reformation. Her works on contemplative prayer, including 'The Interior Castle,' have made her one of the greatest spiritual teachers of the Church. She was named a Doctor of the Church in 1970." },
  { name: "St. John of the Cross", birthYear: "1542", deathYear: "1591", description: "A Spanish mystic and Carmelite priest, St. John co-founded the Discalced Carmelites with St. Teresa of Ávila. He is known for his writings on the 'Dark Night of the Soul,' exploring the path to union with God through suffering and spiritual transformation." },
  { name: "St. Ignatius of Loyola", birthYear: "1491", deathYear: "1556", description:" Founder of the Jesuits" }, 
  { name: "St. Francis Xavier", birthYear: "1506", deathYear: "1552", description:" Jesuit missionary" },    
  { name: "St. Patrick", birthYear:  "0385", deathYear:  "0461", description:" Apostle of Ireland" },  
  { name: "St. Ambrose", birthYear:  "0340", deathYear:  "0397", description:" Bishop of Milan" },  
  { name: "St. Athanasius", birthYear:  "0296", deathYear:  "0373", description:" Defender of the Trinity" },  
  { name: "St. Basil the Great", birthYear:  "0330", deathYear:  "0379", description:" Father of Eastern monasticism" },   
  { name: "St. John Chrysostom", birthYear:  "0347", deathYear:  "0407", description:" Early Church Father" },   
  { name: "St. Leo the Great", birthYear:  "0400", deathYear:  "0461", description:" Pope and Doctor of the Church" },   
  { name: "St. Martin of Tours", birthYear:  "0316", deathYear:  "0397", description:" Bishop and patron of soldiers" },  
  { name: "St. Anthony of Padua", birthYear: "1195", deathYear: "1231", description:" Doctor of the Church" }, 
  { name: "St. Bonaventure", birthYear: "1217", deathYear: "1274", description:" Franciscan theologian" },    
  { name: "St. Albert the Great", birthYear: "1206", deathYear: "1280", description:" Philosopher and scientist" }, 
  { name: "St. Therese of Lisieux", birthYear: "1873", deathYear: "1897", description:"The Little Flower" }, 
  { name: "St. Joan of Arc", birthYear: "1412", deathYear: "1431", description:" French martyr and military leader" },    
  { name: "St. Bernadette Soubirous", birthYear: "1844", deathYear: "1879", description:" Lourdes visionary" }, 
  { name: "St. Elizabeth Ann Seton", birthYear: "1774", deathYear: "1821", description:" First American-born saint" }, 
  { name: "St. Kateri Tekakwitha", birthYear: "1656", deathYear: "1680", description:" First Native American saint" }, 
  { name: "St. Faustina Kowalska", birthYear: "1905", deathYear: "1938", description:" Divine Mercy visionary" }, 
  { name: "St. Maximilian Kolbe", birthYear: "1894", deathYear: "1941", description:" Martyr of Auschwitz" },  
  { name: "St. Edith Stein", birthYear: "1891", deathYear: "1942", description:" Philosopher and martyr" },   
  { name: "St. Teresa of Calcutta", birthYear: "1910", deathYear: "1997", description:" Founder of the Missionaries of Charity" },  
  { name: "St. John Paul II", birthYear: "1920", deathYear: "2005", description:" Pope" },   
  { name: "St. Pio of Pietrelcina (Padre Pio)", birthYear: "1887", deathYear: "1968", description: "A Capuchin friar known for his piety, charity, and bearing the stigmata, Padre Pio dedicated his life to prayer, confession, and spiritual guidance. He was known for his ability to read hearts and for miraculous healings, attracting followers worldwide." },
  { name: "St. Francis de Sales", birthYear: "1567", deathYear: "1622", description:" Doctor of the Church" },  
  { name: "St. Louis de Montfort", birthYear: "1673", deathYear: "1716", description:" Marian theologian" },  
  { name: "St. Alphonsus Liguori", birthYear: "1696", deathYear: "1787", description:" Founder of the Redemptorists" },  
  { name: "St. Vincent de Paul", birthYear: "1581", deathYear: "1660", description:" Patron of charitable societies" },  
  { name: "St. John Bosco", birthYear: "1815", deathYear: "1888", description:" Founder of the Salesians" },    
  { name: "St. Philip Neri", birthYear: "1515", deathYear: "1595", description:" Founder of the Oratory" },    
  { name: "St. Benedict Joseph Labre", birthYear: "1748", deathYear: "1783", description:" Patron saint of homeless people" }, 
  { name: "St. Francis Borgia", birthYear: "1510", deathYear: "1572", description:" Jesuit leader" },  
  { name: "St. Charles Borromeo", birthYear: "1538", deathYear: "1584", description:" Archbishop of Milan" }, 
  { name: "St. Thomas More", birthYear: "1478", deathYear: "1535", description:" Martyr under Henry VIII" },    
  { name: "St. John Fisher", birthYear: "1469", deathYear: "1535", description:" Martyr under Henry VIII" },    
  { name: "St. Rose of Lima", birthYear: "1586", deathYear: "1617", description:" First saint from the Americas" },   
  { name: "St. Damien of Molokai", birthYear: "1840", deathYear: "1889", description:" Apostle to lepers" }, 
  { name: "St. Juan Diego", birthYear: "1474", deathYear: "1548", description:" Visionary of Our Lady of Guadalupe" },     
  { name: "St. Ignatius of Antioch", birthYear:  "0035", deathYear:  "0108", description:" Early martyr and Church Father" }, 
  { name: "St. Polycarp", birthYear:  "0069", deathYear:  "0155", description:" Early martyr and bishop" },    
  { name: "St. Irenaeus of Lyons", birthYear:  "0130", deathYear:  "0202", description:" Early Church Father" }, 
  { name: "St. Justin Martyr", birthYear:  "0100", deathYear:  "0165", description:" Early Christian apologist" },
  { name: "St. Anselm of Canterbury", birthYear: "1033", deathYear: "1109", description: "Doctor of the Church, philosopher, and theologian" },
  { name: "St. Boniface", birthYear: "0675", deathYear: "0754", description: "Apostle of Germany" },
  { name: "St. Gregory of Nazianzus", birthYear: "0329", deathYear: "0390", description: "Doctor of the Church, theologian" },
  { name: "St. Cyril of Alexandria", birthYear: "0376", deathYear: "0444", description: "Patriarch of Alexandria, Doctor of the Church" },
  { name: "St. Cyril of Jerusalem", birthYear: "0313", deathYear: "0386", description: "Bishop of Jerusalem, Doctor of the Church" },
  { name: "St. Ephrem the Syrian", birthYear: "0306", deathYear: "0373", description: "Doctor of the Church, theologian and hymnographer" },
  { name: "St. Hilary of Poitiers", birthYear: "0310", deathYear: "0367", description: "Doctor of the Church, defender of the Trinity" },
  { name: "St. Isidore of Seville", birthYear: "0560", deathYear: "0636", description: "Doctor of the Church, encyclopedist" },
  { name: "St. John Damascene", birthYear: "0675", deathYear: "0749", description: "Doctor of the Church, theologian and hymnographer" },
  { name: "St. Lawrence of Rome", birthYear: "0225", deathYear: "0258", description: "Martyr and deacon of the early Church" },
  { name: "St. Polycarp of Smyrna", birthYear: "0069", deathYear: "0155", description: "Bishop, early martyr, disciple of St. John" },
  { name: "St. Monica", birthYear: "0331", deathYear: "0387", description: "Mother of St. Augustine, patroness of mothers" },
  { name: "St. Cecilia", birthYear: "0200", deathYear: "0230", description: "Patron saint of music and musicians" },
  { name: "St. Agnes of Rome", birthYear: "0291", deathYear: "0304", description: "Virgin and martyr" },
  { name: "St. Perpetua", birthYear: "0182", deathYear: "0203", description: "Early Christian martyr" },
  { name: "St. Felicity", birthYear: "0180", deathYear: "0203", description: "Early Christian martyr, companion of St. Perpetua" },
  { name: "St. Ignatius of Loyola", birthYear: "1491", deathYear: "1556", description: "Founder of the Society of Jesus (Jesuits)" },
  { name: "St. John Vianney", birthYear: "1786", deathYear: "1859", description: "Patron saint of parish priests" },
  { name: "St. Vincent Ferrer", birthYear: "1350", deathYear: "1419", description: "Dominican preacher and missionary" },
  { name: "St. Nicholas of Myra", birthYear: "0270", deathYear: "0343", description: "Bishop, patron of children and sailors" },
  { name: "St. Gregory of Nyssa", birthYear: "0335", deathYear: "0395", description: "Early Church Father, theologian" },
  { name: "St. Clare of Montefalco", birthYear: "1268", deathYear: "1308", description: "Abbess and mystic" },
  { name: "St. Sebastian", birthYear: "0256", deathYear: "0288", description: "Martyr and patron of athletes" },
  { name: "St. George", birthYear: "0275", deathYear: "0303", description: "Martyr and patron saint of England" },
  { name: "St. Lucy", birthYear: "0283", deathYear: "0304", description: "Virgin and martyr, patroness of the blind" },
  { name: "St. Mary Magdalene", birthYear: "-000003", deathYear: "0063", description: "Disciple of Christ and witness to the Resurrection" },
  { name: "St. John the Baptist", birthYear: "-000006", deathYear: "0030", description: "Precursor of Christ, prophet" },
  { name: "St. Andrew the Apostle", birthYear: "0006", deathYear: "0060", description: "Apostle, patron saint of Scotland" },
  { name: "St. James the Greater", birthYear: "0000", deathYear: "0044", description: "Apostle and martyr" },
  { name: "St. Bartholomew the Apostle", birthYear: "0006", deathYear: "0068", description: "Apostle and martyr" },
  { name: "St. Matthew the Apostle", birthYear: "0000", deathYear: "0074", description: "Apostle and Evangelist" },
  { name: "St. Jude Thaddeus", birthYear: "0000", deathYear: "0065", description: "Apostle, patron saint of lost causes" },
  { name: "St. Philip the Apostle", birthYear: "0000", deathYear: "0080", description: "Apostle and martyr" },
  { name: "St. Simon the Zealot", birthYear: "0000", deathYear: "0065", description: "Apostle and martyr" },
  { name: "St. Thomas the Apostle", birthYear: "0001", deathYear: "0072", description: "Apostle, patron of India" },
  { name: "St. Anthony the Great", birthYear: "0251", deathYear: "0356", description: "Father of monasticism" },
  { name: "St. Athanasius of Alexandria", birthYear: "0296", deathYear: "0373", description: "Church Father, defender of the Trinity" },
  { name: "St. Teresa Benedicta of the Cross (Edith Stein)", birthYear: "1891", deathYear: "1942", description: "Jewish convert, martyr" },
  { name: "St. Elizabeth of Hungary", birthYear: "1207", deathYear: "1231", description: "Princess, patron of the poor" },
  { name: "St. Louis of France", birthYear: "1214", deathYear: "1270", description: "King of France, patron of the Third Order of St. Francis" },
  { name: "St. Zita of Lucca", birthYear: "1212", deathYear: "1272", description: "Patroness of domestic workers" },
  { name: "St. Bridget of Sweden", birthYear: "1303", deathYear: "1373", description: "Founder of the Bridgettines, mystic" },
  { name: "St. Margaret of Scotland", birthYear: "1045", deathYear: "1093", description: "Queen of Scotland, patroness of widows" },
  { name: "St. Hedwig of Silesia", birthYear: "1174", deathYear: "1243", description: "Duchess, patron of brides" },
  { name: "St. Gertrude the Great", birthYear: "1256", deathYear: "1302", description: "Mystic and theologian" },
  { name: "St. Juan de la Cruz", birthYear: "1542", deathYear: "1591", description: "Mystic, Doctor of the Church" },
  { name: "St. Ignatius of Antioch", birthYear: "0035", deathYear: "0108", description: "Early Christian martyr and bishop" },
  { name: "St. Polycarp", birthYear: "0069", deathYear: "0155", description: "Bishop, early martyr, disciple of St. John" },
  { name: "St. Charles Lwanga", birthYear: "1860", deathYear: "1886", description: "Ugandan martyr, patron of African youth" },
  { name: "Adam", birthYear: '-004000', deathYear: '-003070', description: "First human, according to the Bible" },
  { name: "Eve", birthYear: '-004000', deathYear: '-003070', description: "First woman, according to the Bible" },
  { name: "Noah", birthYear: '-002940', deathYear: '-001995', description: "Built the Ark, survived the Flood" },
  { name: "Abraham", birthYear: '-002150', deathYear: '-002000', description: "Patriarch of the Israelites, father of Isaac" },
  { name: "Sarah", birthYear: '-002130', deathYear: '-002020', description: "Wife of Abraham, mother of Isaac" },
  { name: "Isaac", birthYear: '-002040', deathYear: '-001822', description: "Son of Abraham, father of Jacob and Esau" },
  { name: "Rebekah", birthYear: '-002030', deathYear: '-001880', description: "Wife of Isaac, mother of Jacob and Esau" },
  { name: "Jacob", birthYear: '-001990', deathYear: '-001837', description: "Patriarch, also called Israel, father of the 12 tribes" },
  { name: "Leah", birthYear: '-001975', deathYear: '-001830', description: "First wife of Jacob, mother of six sons" },
  { name: "Rachel", birthYear: '-001975', deathYear: '-001850', description: "Second wife of Jacob, mother of Joseph and Benjamin" },
  { name: "Joseph", birthYear: '-001910', deathYear: '-001800', description: "Son of Jacob, sold into slavery, became an Egyptian ruler" },
  { name: "Moses", birthYear: '-001391', deathYear: '-001271', description: "Led the Israelites out of Egypt, received the Ten Commandments" },
  { name: "Aaron", birthYear: '-001395', deathYear: '-001273', description: "Brother of Moses, first high priest of the Israelites" },
  { name: "Miriam", birthYear: '-001400', deathYear: '-001270', description: "Sister of Moses and Aaron, prophetess" },
  { name: "Joshua", birthYear: '-001355', deathYear: '-001244', description: "Successor of Moses, led the Israelites into the Promised Land" },
  { name: "Samson", birthYear: '-001150', deathYear: '-001120', description: "Judge of Israel, known for his great strength" },
  { name: "Samuel", birthYear: '-001110', deathYear: '-001010', description: "Prophet and last judge of Israel, anointed Saul and David" },
  { name: "Saul", birthYear: '-001085', deathYear: '-001045', description: "First king of Israel, father of Jonathan and Michal" },
  { name: "David", birthYear: '-001040', deathYear: '-000970', description: "Second king of Israel, slayer of Goliath, father of Solomon" },
  { name: "Jonathan", birthYear: '-001065', deathYear: '-001045', description: "Son of Saul, friend of David" },
  { name: "Bathsheba", birthYear: '-001015', deathYear: '-000950', description: "Wife of David, mother of Solomon" },
  { name: "Solomon", birthYear: '-001010', deathYear: '-000931', description: "King of Israel, known for wisdom, built the First Temple" },
  { name: "Rehoboam", birthYear: '-000972', deathYear: '-000913', description: "Son of Solomon, first king of Judah" },
  { name: "Jeroboam", birthYear: '-000975', deathYear: '-000910', description: "First king of the northern Kingdom of Israel" },
  { name: "Elijah", birthYear: '-000900', deathYear: '-000849', description: "Prophet, defended worship of Yahweh" },
  { name: "Elisha", birthYear: '-000850', deathYear: '-000800', description: "Prophet, successor of Elijah" },
  { name: "Isaiah", birthYear: '-000765', deathYear: '-000695', description: "Prophet, predicted the coming of the Messiah" },
  { name: "Jeremiah", birthYear: '-000650', deathYear: '-000570', description: "Prophet, witnessed the fall of Jerusalem" },
  { name: "Ezekiel", birthYear: '-000622', deathYear: '-000570', description: "Prophet, known for visions including the valley of dry bones" },
  { name: "Daniel", birthYear: '-000620', deathYear: '-000538', description: "Prophet, interpreter of dreams, survived the lions' den" },
  { name: "Hosea", birthYear: '-000785', deathYear: '-000725', description: "Prophet, known for his message of repentance" },
  { name: "Joel", birthYear: '-000835', deathYear: '-000805', description: "Prophet, author of the Book of Joel" },
  { name: "Amos", birthYear: '-000765', deathYear: '-000750', description: "Prophet, known for his call for social justice" },
  { name: "Obadiah", birthYear: '-000850', deathYear: '-000820', description: "Prophet, author of the shortest book in the Old Testament" },
  { name: "Jonah", birthYear: '-000780', deathYear: '-000750', description: "Prophet, swallowed by a great fish" },
  { name: "Micah", birthYear: '-000750', deathYear: '-000687', description: "Prophet, warned of judgment but foretold hope" },
  { name: "Nahum", birthYear: '-000720', deathYear: '-000680', description: "Prophet, foretold the fall of Nineveh" },
  { name: "Habakkuk", birthYear: '-000650', deathYear: '-000620', description: "Prophet, known for dialogue with God about justice" },
  { name: "Zephaniah", birthYear: '-000640', deathYear: '-000610', description: "Prophet, warned of the Day of the Lord" },
  { name: "Haggai", birthYear: '-000520', deathYear: '-000500', description: "Prophet, encouraged rebuilding of the Temple" },
  { name: "Zechariah", birthYear: '-000520', deathYear: '-000480', description: "Prophet, foretold the coming of the Messiah" },
  { name: "Malachi", birthYear: '-000460', deathYear: '-000430', description: "Prophet, called for faithfulness and repentance" },
  { name: "Ezra", birthYear: '-000480', deathYear: '-000440', description: "Priest and scribe, led return of the exiles to Jerusalem" },
  { name: "Nehemiah", birthYear: '-000480', deathYear: '-000430', description: "Governor, rebuilt the walls of Jerusalem" },
  { name: "Esther", birthYear: '-000500', deathYear: '-000460', description: "Queen of Persia, saved the Jews from destruction" },
  { name: "Mordecai", birthYear: '-000500', deathYear: '-000460', description: "Guardian of Esther, helped save the Jews" },
  { name: "Job", birthYear: '-001800', deathYear: '-001700', description: "Subject of the Book of Job, known for his patience in suffering" },
  { name: "Mattathias", birthYear: '-000210', deathYear: '-000166', description: "Priest and father of the Maccabean revolt" },
  { name: "Judas Maccabeus", birthYear: '-000190', deathYear: '-000160', description: "Son of Mattathias, leader of the Maccabean revolt, known for his military prowess" },
  { name: "Jonathan Apphus", birthYear: '-000185', deathYear: '-000143', description: "Brother of Judas Maccabeus, later became high priest and ruler of Judea" },

];